### ISSUE TITLE
DXA HTML Design uses deprecated packages

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-html-design#10]
The HTML Design uses quite a few deprecated packages.
- assemble-contrib-permalinks@0.3.6
- lodash@2.2.1
- lodash@1.0.2
- graceful-fs@1.2.3
- lodash@1.3.1
- graceful-fs@2.0.3
- graceful-fs@3.0.8
- find-file@0.1.4
- jade@0.26.3

**Comment by rpannekoek** [comment]
Use of old, deprecated versions of packages is likely also the reason why we currently can't use the latest version of node. See https://github.com/sdl/dxa-html-design/issues/8

**Comment by rpannekoek** [comment]
TSI-1949 (internal issue ID for tracking purposes)

**Comment by rpannekoek** [comment]
Upgraded NPM packaged in DXA 1.8  (note that this is a moving target, of course).
