### ISSUE TITLE
Cookie notice cookie lifetime is too short

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-html-design#2]
The expiration of the cookie-notice cookie (named "seen-cookie-notice") is set to session. This is too short, a recurring visitor will get to accept the cookie notice again. 

Solution: set the cookie notice cookie to a considerable longer period of time. A lot of sites seem to set the cookie expiration to a year.

**Comment by rpannekoek** [comment]
Fixed in DXA 1.5
