### ISSUE TITLE
Header links in the navbar do not get active

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-html-design#4]
The header links in the navbar of the DXA HTML design do not get class="active" applied in the static example design pages. The stylesheet and class attribute are there but the `this.isCurrentPage` check will never work.

![screenshot](https://cloud.githubusercontent.com/assets/1956935/13244182/8c0c97d2-da04-11e5-811d-af954c4969d3.png)

See design/src/templates/partials/navbar.hbs
https://github.com/sdl/dxa-html-design/blob/master/design/src/templates/partials/navbar.hbs

**Comment by rpannekoek** [comment]
Fixed in DXA 1.5
