### ISSUE TITLE
DXA HTML Design does not build with Node 6

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-html-design#8]
As described in the [README](https://github.com/sdl/dxa-html-design/blob/master/design/README.md) I installed Node JS from https://nodejs.org/. I installed the latest version which today is `Node v6.2.1 Current`.

However with Node 6 the build of the DXA HTML Design will fail on installing the npm packages, the install of `pngquant-bin` fails. See screenshot.

![screenshot npm](https://cloud.githubusercontent.com/assets/1956935/15962539/2504a63a-2f0c-11e6-9746-a4778ded1082.PNG)

The solution is to downgrade and install Node 4. In my case
- uninstall Node v6.2.1 Current
- install Node v4.4.5 LTS

**Comment by bkoopman** [comment]
When you go to the [Node download page](https://nodejs.org/en/download/), the LTS version is actually recommended for most users, but for now I think it indeed makes sense to specify that. For the 1.5 release we will upgrade to npm v3, but there are a lot of grunt packages we should also consider updating which at current isn't planned for.

**Comment by rpannekoek** [comment]
DXA 1.5 README has been updated to make clear that the LTS version must be used.
There is a separate issue for the fact that we are using old, deprecated packages (which is most probably the root cause why Node 6 can currently not be used).
